---
name: Pull request auto update

on:
  push:
    branches:
      - "main"
jobs:
  refresh_stale_prs:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Convert App token
        id: create_token
        uses: getsentry/action-github-app-token@d4b5da6c5e37703f8c3b3e43abb5705b46e159cc # v3.0.0
        with:
          app_id: ${{ vars.DATAHUB_PORTAL_PR_APP_ID }}
          private_key: ${{ secrets.DATAHUB_PORTAL_PR_RW }}
    
      - name: Automatically update PR
        env:
          GITHUB_TOKEN: ${{ steps.create_token.outputs.token }}
        uses: wechuli/pull-request-updater@v2.1.0
        with:
          base: main

