name: Pull Request Auto Update

on:
  push:
    branches:
      - "main"

jobs:
  refresh_stale_prs:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read

    steps:
      - name: Authenticate GitHub CLI
        env:
          GH_TOKEN: ${{ steps.create_token.outputs.token }}
        run: |
          echo $GH_TOKEN | gh auth login --with-token

      - name: Create App Token
        id: create_token
        uses: peter-murray/workflow-application-token-action@v4
        with:
          application_id: ${{ vars.DATAHUB_PORTAL_PR_APP_ID }}
          application_private_key: ${{ secrets.DATAHUB_PORTAL_PR_RW }}

      - name: Get Latest SHA of Base Branch (main)
        id: get_main_sha
        run: |
          latest_sha=$(gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/fsdh-cdsf/datahub-portal/branches/main | jq -r '.commit.sha')
          echo "Latest SHA of main branch: $latest_sha"
          echo "latest_sha=$latest_sha" >> $GITHUB_OUTPUT

      - name: Update PR Branch
        run: |
          gh api \
            --method PUT \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/fsdh-cdsf/datahub-portal/pulls/2/update-branch \
            -f "expected_head_sha=${{ steps.get_main_sha.outputs.latest_sha }}"
