---
name: Pull request auto update

on:
  push:
    branches:
      - "main"
jobs:
  refresh_stale_prs:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Create App token
        id: create_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.DATAHUB_PORTAL_PR_APP_ID }}
          private-key: ${{ secrets.DATAHUB_PORTAL_PR_RW }}

      - name: Automatically update PR
        uses: wechuli/pull-request-updater@v2.1.0
        with:
          token: ${{ steps.create_token.outputs.token }}
          base: main

