---
name: Pull request auto update

on:
  push:
    branches:
      - "main"
jobs:
  refresh_stale_prs:
    runs-on: ubuntu-latest
    steps:
      - name: Create App token
        id: create_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.DATAHUB_PORTAL_PR_APP_ID }}
          private-key: ${{ secrets.DATAHUB_PORTAL_PR_RW }}
          owner: ${{ github.repository_owner }}
          repositories: "data-portal"
          

      - name: Automatically update PR
        uses: adRise/update-pr-branch@v0.9.1
        with:
          token: ${{ steps.create_token.outputs.token }}
          base: "main"
          required_approval_count: 0
          require_passed_checks: false
          allow_ongoing_checks: true
          sort: "created"
          direction: "desc"
          require_auto_merge_enabled: false
